cmcuza/TerseTS

.github/workflows/zig-build-lint-and-test-on-pr-and-push.yml

This PR adds a adds name to the `zig_lint` GitHub Actions job.

Add name to zig_lint

---

bindings/python/tersets/__init__.py
bindings/python/tests/__init__.py
src/tersets.zig

This PR finish implementation of the initial interface for the library by adding the `decompress()` function and `Configuration` struct and updates the Python bindings to match. To allow the interface to be tested, a placeholder "compression" method is implemented that simply reinterpret the 64-bit floating-point values as bytes for compression and reverse for decompression. Of course this placeholder should be removed when the real compression methods are added.

Add decompress() and Configuration

---

.github/workflows/zig-build-lint-and-test-on-pr-and-push.yml
tools/pre-commit

Add `ReleaseFast` to the GitHub Actions workflow and a Git `pre-commit` hook that run the same tools locally to help avoid creating commits that does not pass.

Add ReleaseFast

---

.github/workflows/zig-build-lint-and-test-on-pr-and-push.yml
.gitignore
README.md
bindings/c/tersets.h
tools/pre-commit

This PR adds a header file that can be used in C-based languages like C, C++, and Objective-C. Thus, making TerseTS directly usable from these languages without having to manually define prototypes.

Add header for languages like C, C++, and Obj-C

---

.github/workflows/zig-build-lint-and-test-on-pr-and-push.yml
build.zig
src/capi.zig
src/functional/poor_mans_compression.zig
src/functional/poor_mans_compression_midrange.zig
src/tersets.zig

This PR simplify the implementation of the interface by splitting it into `src/tersets.zig` for the Zig API and `src/capi.zig` for the C API. Thus, `src/tersets.zig` implements all of the functionality for executing the correct method while `src/capi.zig` implements all of the functionality for using TerseTS through C. These changes where made while implementing Poor Man's Compression Midrange and Poor Man's Compression Mean which is also included in this PR. Both Midrange and Mean is implemented in `src/functional/poor_mans_compression.zig` as their only difference is the compression method, so implementing them in different files would either require a lot of duplicate code or require a separate file with the bulk of the code and two files containing only the compression methods. The …

Clean interface and add Poor Man's Compression

---

src/capi.zig
src/functional/geometry/convex_hull.zig
src/functional/swing_slide_filter.zig
src/tersets.zig

This PR contains the Graham algorithm [1] for incrementally maintaining a convex hull defined by a lower and upper hull. We define the lower and upper hulls as point sets and create a new structure to manipulate the points. The PR also changes `src/capi.zig` adding a new kind of error to the Error list of TerseTS.
[1] Mark De Berg, and Marc van Kreveld. Computational geometry: algorithms and applications. Third Edition. Springer Science & Business Media, 2000. https://doi.org//10.1007/978-3-540-77974-2.

Add convex hull primitives

---

bindings/python/tersets/__init__.py
src/tersets.zig

This PR converts the two remaining TODOs in the source code into GitHub issues so issues are managed consistently. The two new issues are #34 which replaces `TODO: Specify that TerseTS's timestamps are the values indices.` from `src/tersets.zig` and #36 which replaces `TODO: Handle different errors from TerseTS.` from `bindings/python/tersets/__init__.py`.

Remove remaining TODOs from the source code

---

src/functional/poor_mans_compression.zig
src/functional/swing_slide_filter.zig
src/tersets.zig

This PR closes #23 by changing the names of the `compress_` functions to [camelCase](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Examples_of_multiple-word_identifier_formats).

Make compress_* functions match other functions

---

src/functional/geometry/convex_hull.zig
src/functional/swing_slide_filter.zig
src/tersets.zig

This PR implements a generic function to create Points and Segments in TerseTS. Currently, "Swing Filter" only requires discrete time-axis points and segments, however, "Slide Filter" requires continuous time-axis points and segments. Based on the comments made by @skejserjensen in https://github.com/cmcuza/TerseTS/pull/38#issue-2344112220, such a generic function allows us to create more effective structures depending on the needs of each compression method. Thus, https://github.com/cmcuza/TerseTS/pull/38#issue-2344112220 was closed and this new PR was created.

Add generic Point and Segment structure

---

src/capi.zig
src/functional/geometry/convex_hull.zig
src/functional/swing_slide_filter.zig
src/tersets.zig

This PR adds the Slide Filter compression algorithm from the paper [1] and Closes #30. We have slightly modified the proposed method in two main aspects. 1) The slope of the linear approximation does not minimize the squared error of the points in the segment. 2) Any two consecutive linear approximations are disjointed—these two changes are necessary due to the paper's imprecision. 
1) To compute the slope with minimum squared error the starting point needs to be known from the beginning however, in Slide Filter the starting point depends on the continuously updated upper and lower bounds as well as alpha and beta as explained in Lines 19, and 20 of Alg 2. A simple and efficient solution is to compute the slope as the mean of the upper and lower bounds' slopes. This solution satisfies Eq. …

Add Slide Filter 

---

README.md
bindings/python/tersets/__init__.py
bindings/python/tests/__init__.py

This PR fills the TODO in the Usage section of the Readme and Closes #18. An example of how to use TerseTS from C and Python is provided.

Add usage example in Readme.md

---

README.md
bindings/python/tersets/__init__.py
bindings/python/tests/__init__.py
src/capi.zig
src/functional/sim_piece.zig
src/tersets.zig
src/tester.zig

This PR adds the Sim-Piece compression algorithm from the paper [1] and Closes #19. The implementation is based on the authors' implementation at https://github.com/xkitsios/Sim-Piece (accessed 19-06-24). Few changes were made to support
an error bound equal to zero and to improve numerical stability. This is because Sim-Piece does not support lossless compression. Setting `error_bound` to zero will cause an error due to undefined quantization (`b=floor(value/error_bound)*error_bound`). This has a ripple effect across the algorithm that demands the implementation of special instructions to handle a zero error bound. Nevertheless, the numerical instabilities inherent to floating point operations mean that decompressed values will not exactly match the original uncompressed values. To alert …

Add Sim-Piece

---

.gitignore
build.zig

This PR fix two issues caused by Zig release 0.12.0 and 0.13.0. [Zig 0.12.0](https://ziglang.org/download/0.12.0/release-notes.html#introduce-bpath-deprecate-LazyPathrelative) introduces `b.path`, thus `build.zig` had to be updated as explained in the release notes. [Zig 0.13.0](https://ziglang.org/download/0.13.0/release-notes.html#codezig-cachecode-renamed-to-codezig-cachecode) changes the name of `zig-cache` to `.zig-cache`, thus `.gitignore` had to be updated. Also, while not related to the new releases of Zig, `*.pch` has been added to `.gitignore` so both GCC's and Clang's [precompiled headers](https://en.wikipedia.org/wiki/Precompiled_header) are ignored. Finally, the `.gitignore` file has been sorted so it is easier to find items.

Fix issues caused by new Zig releases

---

.gitignore
bindings/python/README.md
bindings/python/setup.py

This PR finishes #52 by resolving the issues with `python -m pip install .` mentioned in the reviews of #61 in preparation for #62. The core issue solved by this PR is to copy `src` to the correct place and delete it afterwards no matter which order the `setuptools` commands are run in. This problem occurs because `python -m build` runs the `setuptools` commands `egg_info`, `sdist`, `egg_info`, `check`, `egg_info`, `bdist_wheel`, `build`, `build_py`, `egg_info`, and `build_ext` if `src` does not exist while  `python -m pip install .` runs the `setuptools` commands `bdist_wheel`, `build`, `build_py`, `egg_info`, and `build_ext` if `src` does not exist. Thus, both `sdist` and `bdist_wheel` have been extended to copy the `src` directory and then delete it again. In addition, checks have been …

Add support for python -m pip install

---

.github/workflows/zig-build-lint-and-test-on-pr-and-push.yml
bindings/python/tersets/__init__.py
build.zig
src/functional/histogram_compression.zig
src/functional/sim_piece.zig
src/functional/swing_slide_filter.zig
src/tersets.zig
src/tester.zig
src/utilities/convex_hull.zig
src/utilities/hashed_priority_queue.zig

This PR fixes two issues caused by Zig release 0.14.0. First, [Zig 0.14.0](https://ziglang.org/download/0.14.0/release-notes.html#Remove-Anonymous-Struct-Types-Unify-Tuples) changes the type of "untyped anonymous struct literals" such as `const x = .{ .a = 123 }` from "anonymous struct type" to "normal struct type". Second, [Zig 0.14.0](https://ziglang.org/download/0.14.0/release-notes.html#List-of-Deprecations) `std.rand` has been renamed to `std.Random`.

Fix issues caused by new Zig release

---

bindings/python/tersets/__init__.py
src/capi.zig
src/functional/histogram_compression.zig
src/functional/swing_slide_filter.zig
src/tersets.zig
src/tester.zig

This PR reimplements the Swing Filter algorithm to follow its original paper [1]. Specifically, the current implementation created disconnected segments, while in the proposed algorithm [1], the segments are connected by taking the previous endpoint as the first endpoint of the segment. This has advantages and disadvantages; therefore, we now include both implementations and let the user decide which one they want. The previous Swing Filter implementation is now called "Swing Filter Disconnected", while the originally proposed method is called "Swing Filter". Since [1] mentions the possibility of disconnecting the segments, and since both methods are interesting and produce different results, I believe their implementations belong in the same file.     
This PR also adds the necessary …

Fix Swing Filter Implementation

---

src/capi.zig
src/functional/histogram_compression.zig
src/functional/poor_mans_compression.zig
src/functional/sim_piece.zig
src/functional/swing_slide_filter.zig
src/tersets.zig
src/tester.zig

This PR proposes a quick fix to the random generation process that was producing NaN values. These NaN values were later making the test fail, so in theory, now all tests should pass without problem. This PR closes issue #72.

Fix random generation function

---

.github/workflows/zig-build-lint-and-test-on-pr-and-push.yml

This PR closes #53, transitioning our GitHub workflow actions from `goto-bus-stop/setup-zig` to `mlugg/setup-zig`.

Transition from `goto-bus-stop/setup-zig` to `mlugg/setup-zig`

---

src/utilities/hashed_priority_queue.zig

Correct boundary conditions in `removeIndex` and `get`.

Fix bounds checks in hashed priority queue

---

bindings/python/tersets/__init__.py
src/capi.zig
src/line_simplification/sliding_window.zig
src/tersets.zig

This PR implements the sliding window compression algorithm following [1] related to #66. Besides the implementation of the `compress` and `decompress` functions and the necessary testing, this PR also includes an additional cost function to tease with the idea of adding a parametrization of the `compress` function to include different error bounds or, as in this case, include different cost functions. This is related to #55, and I will address it next.
[1] https://doi.org/10.1109/ICDM.2001.989531

Add sliding window line simplication

---

.github/CONTRIBUTING.md
src/functional_approximation/abc_linear_approximation.zig
src/functional_approximation/mix_piece.zig
src/functional_approximation/poor_mans_compression.zig
src/functional_approximation/sim_piece.zig
src/functional_approximation/swing_slide_filter.zig
src/histogram_representation/constant_linear_representation.zig
src/line_simplification/bottom_up.zig
src/line_simplification/sliding_window.zig
src/line_simplification/visvalingam_whyatt.zig
src/lossless_encoding/run_length_encoding.zig
src/quantization/bitpacked_quantization.zig
src/tersets.zig
src/utilities/shared_functions.zig

This PR moves the `isWithinErrorBound` function from `src/tersets.zig` file to the file `src/utilities/shared_functions.zig` for consistency and better structuring. 
- Almost all were modified to switch from `tersets.isWithinErrorBound` to `shared_functions.isWithinErrorBound`.
- No new tests added.

Move isWithinErrorBound function to `shared_functions.zig` 

---

.github/workflows/zig-build-lint-and-test-on-pr-and-push.yml

In a previous PR, I got the job failed with the error: error: failed to spawn build runner C:\Users\runneradmin\AppData\Local\zig\o\7e48997dfe81227c2fec25ad9d476202\build.exe: FileNotFound
This happens when running zig build commands in the workflow. The most likely cause is that Zig is unable to find or generate build.exe in the cache directory, possibly due to a corrupted Zig cache or a previous failed build..
Add a step before the Zig build steps to clear Zig’s local cache on Windows runners. You can do this by inserting the following step in your workflow before running any zig build command:
- name: Clear Zig Cache 
run: Remove-Item -Recurse -Force "$env:LOCALAPPDATA\zig" -ErrorAction SilentlyContinue
shell: pwsh

Clear Zig’s local cache on runners
